### ISSUE TITLE
spacing below `h3`s too large

### ISSUE THREAD

**Issue by benpeter** [hlxsites/servicenow#83]
servicenow.com

<img width="1220" alt="image" src="https://github.com/hlxsites/servicenow/assets/398734/8995b4d7-3a88-46d0-a7b3-d5f505ec571e">

main

<img width="1226" alt="image" src="https://github.com/hlxsites/servicenow/assets/398734/be1f691e-ca52-4dde-85ef-97c666aaaa1a">

**Comment by andreituicu** [comment]
Just to voice my personal opinion here, in the end the customer would have to make the final call, so let's keep the issue open: 🙂
Yes, it is different than the original website, but I kind of think that it is better like this. because on pages like topic/category/year, the sidebar and main content align nicely at the top:
Original https://www.servicenow.com/blogs/topics/ai-and-automation.html :
<img width="1289" alt="Screenshot 2023-11-15 at 21 35 13" src="https://github.com/hlxsites/servicenow/assets/3651689/4c8b4bf2-48f7-4323-b061-828cedc5583a">

vs. now in Franklin, without fixing it https://main--servicenow--hlxsites.hlx.live/blogs/topics/ai-and-automation:
<img width="1228" alt="Screenshot 2023-11-15 at 21 37 28" src="https://github.com/hlxsites/servicenow/assets/3651689/1f1143f6-8edf-4035-a3fc-6c4febb74da2">

**Comment by benpeter** [comment]
I would argue
1. it's probably going to take longer to get a decision on that than: fix to mimic as-is and maybe optimise later
2. within articles, the spacing doesn't look natural to the eye (mine at least) - the h3 is closer to the preceding paragraph than the next

from https://main--servicenow--hlxsites.hlx.page/blogs/2023/demo/3-ways-enhance-digital-experiences
![image](https://github.com/hlxsites/servicenow/assets/398734/7d7b74df-a7da-4ef4-96f0-daec76f625af)

**Comment by andreituicu** [comment]
@benpeter in this last example, there is an extra `<br>` in the word document, causing it to look like this:
<img width="905" alt="Screenshot 2023-11-16 at 17 21 47" src="https://github.com/hlxsites/servicenow/assets/3651689/ddcb4f67-13b8-4c97-b176-c794dff18b45">

**Comment by benpeter** [comment]
thanks @andreituicu !

**Comment by benpeter** [comment]
@andreituicu  the `<br/>` is there in servicenow.com as well though and doesn't create that amount of spacing:

![image](https://github.com/hlxsites/servicenow/assets/398734/008bcfe5-bce4-4c46-a81c-549bcfc7cde0)

**Comment by andreituicu** [comment]
yes, because my understand is they were using new lines to create spacing, while we should be using CSS. (don't know if it is even possible to insert brs at beginning of paragraphs manually in the word doc via keyboard, but if you copy paste it like I did from the original, it gets added). It is something that I have pending to clarify, but from my tries on word, I wasn't able to add brs with either ENTER or SHIFT + ENTER at the beginning of a paragraph, so for now in the import script I'm removing them and relying on CSS: https://github.com/hlxsites/servicenow/blob/importer/tools/importer/import.js#L153 .

If you can successfully introduce them manually, please let me know and we can revisit the import. Otherwise, we shouldn't rely on something that authors can't do for styling and think only in CSS terms.

(I could argue that authors should not have to add new lines anyway to achieve correct styling, because the styling of all blog pages should be consistent)

**Comment by benpeter** [comment]
understood, thank @andreituicu -- I wasn't aware these haven't imported but copy/pasted.
Fully agree we shouldn't rely on something the authors can't intuitively accomplish!

**Comment by benpeter** [comment]
so @andreituicu - are we closing this as not planned then?
